# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queens', models.IntegerField(default=0)),
                ('algorithm', models.CharField(default='0', max_length=200)),
                ('time', models.FloatField(default=0)),
            ],
        ),
    ]
